package alibabacloud

import "github.com/godeps/aigo/engine"

// ModelInfos returns i18n metadata for all Alibaba Cloud Bailian models.
func ModelInfos() []engine.ModelInfo {
	return []engine.ModelInfo{
		{
			Name:        ModelQwenImage,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen Image", "zh": "通义万相文生图"},
			Description: engine.DisplayName{"en": "Text-to-image generation", "zh": "文本生成图片"},
			Intro:       engine.DisplayName{"en": "Tongyi Wanxiang text-to-image model leveraging Qwen's multimodal capabilities to produce vivid, high-resolution images from natural language prompts across artistic and photographic styles.", "zh": "通义万相文生图模型，基于通义千问多模态能力，从自然语言提示词生成高分辨率图片，支持艺术和写实多种风格。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "image",
		},
		{
			Name:        ModelQwenImage2,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen Image 2.0", "zh": "通义万相 2.0"},
			Description: engine.DisplayName{"en": "Enhanced text-to-image generation", "zh": "增强版文本生成图片"},
			Intro:       engine.DisplayName{"en": "Upgraded Tongyi Wanxiang 2.0 model with improved prompt adherence, richer detail, and enhanced color fidelity for professional creative and commercial use.", "zh": "通义万相 2.0 升级版，提示词遵循度更高、细节更丰富、色彩还原更好，适用于专业创意和商业场景。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "image",
		},
		{
			Name:        ModelQwenImageEditPlus,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen Image Edit Plus", "zh": "通义万相图片编辑"},
			Description: engine.DisplayName{"en": "AI-powered image editing", "zh": "AI 图片编辑"},
			Intro:       engine.DisplayName{"en": "Advanced AI image editing model supporting inpainting, outpainting, and style transfer to precisely modify existing images while preserving overall composition.", "zh": "高级 AI 图片编辑模型，支持局部重绘、扩图和风格迁移，在保持整体构图的同时精确修改图片内容。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "image_edit",
		},
		{
			Name:        ModelWanImage,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Wan 2.7 Image", "zh": "万象 2.7 图像"},
			Description: engine.DisplayName{"en": "Wan model image generation", "zh": "万象模型图片生成"},
			Intro:       engine.DisplayName{"en": "Wan 2.7 image generation model optimized for photorealistic and artistic outputs with strong multi-language prompt understanding and fine-grained visual control.", "zh": "万象 2.7 图像生成模型，针对写实和艺术风格优化，具备强大的多语言提示理解和精细视觉控制能力。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "image",
		},
		{
			Name:        ModelZImageTurbo,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Z-Image Turbo", "zh": "Z-Image 极速版"},
			Description: engine.DisplayName{"en": "Fast image generation", "zh": "快速图片生成"},
			Intro:       engine.DisplayName{"en": "High-speed image generation model designed for low-latency applications, delivering quality results within seconds for prototyping and high-throughput creative workflows.", "zh": "高速图片生成模型，专为低延迟应用设计，数秒内输出优质结果，适合原型设计和高吞吐量创意工作流。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "image",
		},
		{
			Name:        ModelWanTextToVideo,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Wan 2.7 Text-to-Video", "zh": "万象 2.7 文生视频"},
			Description: engine.DisplayName{"en": "Text-to-video generation", "zh": "文本生成视频"},
			Intro:       engine.DisplayName{"en": "Wan 2.7 text-to-video model generating cinematic-quality video clips from text prompts with consistent motion and scene coherence, suitable for creative storytelling and advertising.", "zh": "万象 2.7 文生视频模型，从文字提示生成影视级视频片段，具备连贯的动作和场景一致性，适合创意叙事和广告制作。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video",
		},
		{
			Name:        ModelWanImageToVideo,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Wan 2.7 Image-to-Video", "zh": "万象 2.7 图生视频"},
			Description: engine.DisplayName{"en": "Image-to-video generation", "zh": "图片生成视频"},
			Intro:       engine.DisplayName{"en": "Wan 2.7 image-to-video model animating static images into fluid video sequences with natural motion synthesis, ideal for bringing photographs and illustrations to life.", "zh": "万象 2.7 图生视频模型，将静态图片动画化为流畅视频序列，具备自然动作合成，适合为照片和插图赋予生命。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video",
		},
		{
			Name:        ModelWanReferenceVideo,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Wan 2.7 Reference Video", "zh": "万象 2.7 参考视频"},
			Description: engine.DisplayName{"en": "Reference-driven video generation", "zh": "参考视频生成"},
			Intro:       engine.DisplayName{"en": "Reference-driven video generation model that uses a source video as a style or motion reference, enabling consistent character or scene reproduction in new video outputs.", "zh": "参考视频生成模型，以源视频作为风格或动作参考，在新视频输出中实现一致的角色或场景复现。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video",
		},
		{
			Name:        ModelWanVideoEdit,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Wan 2.7 Video Edit", "zh": "万象 2.7 视频编辑"},
			Description: engine.DisplayName{"en": "AI-powered video editing", "zh": "AI 视频编辑"},
			Intro:       engine.DisplayName{"en": "AI video editing model enabling precise modifications to existing videos including object replacement, background changes, and style transformation while maintaining temporal consistency.", "zh": "AI 视频编辑模型，支持对现有视频进行精确修改，包括物体替换、背景更换和风格转换，同时保持时序一致性。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video_edit",
		},
		{
			Name:        ModelKlingV3Video,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Kling V3 Video", "zh": "可灵 V3 视频"},
			Description: engine.DisplayName{"en": "Kling V3 video generation via DashScope", "zh": "通过百炼调用可灵 V3 视频生成"},
			Intro:       engine.DisplayName{"en": "Kling V3 video generation accessed via Alibaba Cloud DashScope, combining Kuaishou's advanced video synthesis with DashScope's enterprise-grade API reliability.", "zh": "通过阿里云百炼平台调用的可灵 V3 视频生成，结合快手先进视频合成能力与百炼企业级 API 可靠性。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video",
		},
		{
			Name:        ModelKlingV3OmniVideo,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Kling V3 Omni Video", "zh": "可灵 V3 全能视频"},
			Description: engine.DisplayName{"en": "Kling V3 omni video generation via DashScope", "zh": "通过百炼调用可灵 V3 全能视频生成"},
			Intro:       engine.DisplayName{"en": "Kling V3 Omni all-in-one video generation via DashScope supporting text-to-video and image-to-video in a single unified model with cinematic output quality.", "zh": "通过百炼调用的可灵 V3 全能视频生成，单一统一模型支持文生视频和图生视频，输出影视级画质。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "video",
		},
		{
			Name:        ModelQwenTTSFlash,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen TTS Flash", "zh": "通义语音合成极速版"},
			Description: engine.DisplayName{"en": "Fast text-to-speech synthesis", "zh": "快速文本转语音"},
			Intro:       engine.DisplayName{"en": "Ultra-low-latency Qwen TTS Flash model delivering natural-sounding speech in milliseconds, optimized for real-time voice assistants and interactive applications.", "zh": "超低延迟通义语音合成极速版，毫秒级输出自然语音，专为实时语音助手和互动应用优化。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "tts",
		},
		{
			Name:        ModelQwenTTSInstructFlash,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen TTS Instruct Flash", "zh": "通义语音合成指令极速版"},
			Description: engine.DisplayName{"en": "Instruction-guided fast TTS", "zh": "指令引导快速语音合成"},
			Intro:       engine.DisplayName{"en": "Instruction-guided fast TTS model allowing fine-grained control over speaking style, emotion, and pace via natural language instructions while maintaining ultra-low latency.", "zh": "指令引导快速语音合成模型，通过自然语言指令精细控制说话风格、情感和语速，同时保持超低延迟。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "tts",
		},
		{
			Name:        ModelQwenVoiceDesign,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen Voice Design", "zh": "通义声音设计"},
			Description: engine.DisplayName{"en": "Custom voice design", "zh": "自定义声音设计"},
			Intro:       engine.DisplayName{"en": "Creative voice design model enabling users to craft unique AI voices with customizable characteristics including gender, age, accent, and emotional tone for brand and entertainment use.", "zh": "创意声音设计模型，支持用户定制包括性别、年龄、口音和情感音调在内的独特 AI 声音，适用于品牌和娱乐场景。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "voice_design",
		},
		{
			Name:        ModelQwenASRFlash,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen ASR Flash", "zh": "通义语音识别极速版"},
			Description: engine.DisplayName{"en": "Fast speech recognition", "zh": "快速语音识别"},
			Intro:       engine.DisplayName{"en": "High-speed Qwen ASR Flash model with sub-second transcription latency supporting multiple languages and dialects, optimized for real-time voice input in applications.", "zh": "高速通义语音识别极速版，亚秒级转写延迟，支持多语种和方言，专为应用中的实时语音输入优化。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "asr",
		},
		{
			Name:        ModelQwenASRFlashFiletrans,
			Provider:    "alibabacloud",
			DisplayName: engine.DisplayName{"en": "Qwen ASR File Transcription", "zh": "通义语音文件转写"},
			Description: engine.DisplayName{"en": "Audio file transcription", "zh": "音频文件转写"},
			Intro:       engine.DisplayName{"en": "Batch audio file transcription model supporting long-form recordings up to hours in length with speaker diarization, timestamps, and high accuracy across noisy environments.", "zh": "批量音频文件转写模型，支持长达数小时的录音，具备说话人分离、时间戳和在嘈杂环境中的高准确率。"},
			DocURL:      "https://help.aliyun.com/zh/model-studio/getting-started/models",
			Capability:  "asr",
		},
	}
}
